In [2]:
# https://drive.google.com/file/d/1p9BfIl6I7TCVsXYubbYLwo65SWUp-JdB/view
!gdown --id 1p9BfIl6I7TCVsXYubbYLwo65SWUp-JdB

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1p9BfIl6I7TCVsXYubbYLwo65SWUp-JdB
To: /content/housing.csv
100% 1.06M/1.06M [00:00<00:00, 75.9MB/s]


In [3]:
import pandas as pd
df = pd.read_csv('housing.csv')
df=df.dropna()


# Linear Regression
Tìm hàm :

\begin{aligned}
 &Y_{i}=\beta_{1}+\beta_{2} X_{2 i}+\beta_{3} X_{3 i}+\ldots+\beta_{k} X_{k i}+u_{i}\\
\end{aligned}
\begin{aligned}
\\
&\left\{\begin{array}{l}
Y_{1}=\beta_{1}+\beta_{2} X_{21}+\beta_{3} X_{31}+\ldots+\beta_{k} X_{k 1}+u_{1} \\
Y_{2}=\beta_{1}+\beta_{2} X_{22}+\beta_{3} X_{32}+\ldots+\beta_{k} X_{k 2}+u_{2} \\
\cdots \cdots \cdots \cdots \cdots \cdots \cdots \cdots \cdots \cdots \cdots \cdots \cdots \cdots \cdots \cdots \cdots \cdots \cdots \\
Y_{\mathrm{n}}=\beta_{1}+\beta_{2} X_{2 n}+\beta_{3} X_{3 \mathrm{n}}+\ldots+\beta_{\mathrm{k}} X_{k n}+u_{n}
\end{array}\right.\\
&\mathrm{Y}=\left(\begin{array}{c}
\mathrm{Y}_{1} \\
\mathrm{Y}_{2} \\
\cdot \\
\cdot \\
\mathrm{Y}_{\mathrm{n}}
\end{array}\right) ; \mathrm{X}=\left(\begin{array}{ccccc}
1 & \mathrm{X}_{21} & \mathrm{X}_{31} & \ldots & \mathrm{X}_{\mathrm{k} 1} \\
1 & \mathrm{X}_{22} & \mathrm{X}_{32} & \ldots & \mathrm{X}_{\mathrm{k} 2} \\
. & \cdot & . & \ldots & . \\
. & \cdot & . & \ldots & \\
1 & \mathrm{X}_{2 \mathrm{n}} & \mathrm{X}_{3 \mathrm{n}} & & \mathrm{X}_{\mathrm{kn}}
\end{array}\right)\\
&\mathrm{u}=\left(\begin{array}{c}
\mathrm{u}_{1} \\
\mathrm{u}_{2} \\
\cdot \\
\cdot \\
\mathrm{u}_{\mathrm{n}}
\end{array}\right) ; \beta=\left(\begin{array}{c}
\beta_{1} \\
\beta_{2} \\
\cdot \\
\cdot \\
\beta_{\mathrm{n}}
\end{array}\right)
\end{aligned}
Với a, b sao cho trung bình của bình phương sai số nhỏ nhất.
Tức là:

$ \frac{1}{n} \sum (Y-\hat{Y})^2 = \frac{1}{n} (Y- aX - b)^2$ đạt giá trị nhỏ nhất (*)

Nghiệm của bài toán này:

Z là ma trận rộng của X thêm 1 cột toàn 1.

$(Z^TZ)^{-1}Z^TY$


In [16]:
import numpy as np
X=df.iloc[:,[1,2,3,4,5,6]]
Z = np.concatenate([ np.ones((len(X), 1)),X], axis = -1)
Z

array([[1.0000e+00, 4.1000e+01, 8.8000e+02, ..., 3.2200e+02, 1.2600e+02,
        8.3252e+00],
       [1.0000e+00, 2.1000e+01, 7.0990e+03, ..., 2.4010e+03, 1.1380e+03,
        8.3014e+00],
       [1.0000e+00, 5.2000e+01, 1.4670e+03, ..., 4.9600e+02, 1.7700e+02,
        7.2574e+00],
       ...,
       [1.0000e+00, 1.7000e+01, 2.2540e+03, ..., 1.0070e+03, 4.3300e+02,
        1.7000e+00],
       [1.0000e+00, 1.8000e+01, 1.8600e+03, ..., 7.4100e+02, 3.4900e+02,
        1.8672e+00],
       [1.0000e+00, 1.6000e+01, 2.7850e+03, ..., 1.3870e+03, 5.3000e+02,
        2.3886e+00]])

In [5]:
Y = df['median_house_value'].values
Y = Y.reshape(-1, 1)
Y

array([[452600.],
       [358500.],
       [352100.],
       ...,
       [ 92300.],
       [ 84700.],
       [ 89400.]])

In [8]:
L=np.matmul(np.matmul(np.linalg.inv(np.matmul(X.T, X)), X.T), Y)
L

array([[-4.61396473e+04],
       [ 1.88212143e+03],
       [-1.97331147e+01],
       [ 1.00943796e+02],
       [-3.53190219e+01],
       [ 1.24803173e+02],
       [ 4.77483808e+04]])

Tiếp tục từ (*)

$ L = \frac{1}{n} \sum (Y-\hat{Y})^2 = \frac{1}{n} (Y- aX - b)^2$
L đạt giá trị nhỏ nhất

Đặt: $\lambda$ là learning rate.

a, b sẽ được cập nhật bằng công thức sau:

*   $a = a - \lambda \frac{\partial L}{\partial a} = a - \lambda \frac{2 (Y-aX-b)(-X)}{n}$
*   $b= b - \lambda \frac{\partial L}{\partial b} = b - \lambda \frac{2 (Y-aX-b) (-1)}{n}$

Điều kiện dừng:

1. Chạy cố định bao nhiêu vòng lặp.
2. Sai số giữa a,b với biến cập nhật mới của nó nhỏ hơn một số cho trước (10^-6). $abs(a - \bar{a}) < 10 ^{-6}$ hoặc $\frac{\bar{a}}{a} < 10^{-6}$
3. $abs(L(a,b) - L(\bar{a}, \bar{b})) < 10^{-6} $ hoặc $abs(\frac{L(\bar{a},\bar{b})}{L(a,b)})<10^{-6}$

Nên lúc nào cũng kèm theo đk 1.





In [14]:
# Dựa trên để code

import numpy as np

# init
a = 1
b = 100
num_itr = 53 # Số vòng lặp
lr = 0.0001 # learing rate.

for itr in range(num_itr):
    a = a - lr * 2 * np.mean((Y - a* X -b )*(-X))
    b = b - lr * 2 * np.mean((Y - a* X -b )*(-1))

    if not itr % 10:
        loss = np.mean(np.square(Y - a*X - b))
        print(f'{itr} iter : {loss}')
        print("\na ",a ,"\b ",b)

# final
loss = np.mean(np.square(Y - a*X - b))
print("\nloss",loss)

0 iter : 2158337762417781.8

a  30891.395173976078   -4388.437259119512
10 iter : 2.9074532967205427e+68

a  1.1312748663639402e+31   -1.6552060185097894e+30
20 iter : 3.9166564254321243e+121

a  4.152116237636293e+57   -6.0750998633755925e+56
30 iter : 5.276163015991235e+174

a  1.523950523735642e+84   -2.2297428801771746e+83
40 iter : 7.107566543379505e+227

a  5.593353041860511e+110   -8.183821539582527e+109
50 iter : 9.57466666883811e+280

a  2.0529274253733773e+137   -3.0037066420148423e+136

loss 4.045798129225641e+291


In [15]:
from sys import breakpointhook
# Dựa trên để code thêm đk dừng 2,3

import numpy as np

# init
a = 1
b = 100
num_itr =53 # Số vòng lặp
lr = 0.0001 # learing rate.
er = 10 ** (-6)

for itr in range(num_itr):
    a_update = a - lr * 2 * np.mean((Y - a* X -b )*(-X))
    b_update = b - lr * 2 * np.mean((Y - a* X -b )*(-1))

    # ĐK 2
    if abs(a-a_update) < er and abs(b-b_update) < er:
        break
    
    # ĐK 3:
    if abs(np.mean(np.square(Y - a*X - b)) - np.mean(np.square(Y - a_update*X - b_update))) < er:
        loss = np.mean(np.square(Y - a*X - b))
        print(f'{itr - 1} iter : {loss}')
        break
    a = a_update 
    b = b_update 

    if not itr % 10:
        loss = np.mean(np.square(Y - a*X - b))
        print(f'{itr} iter : {loss}')

loss = np.mean(np.square(Y - a*X - b))
print("\nloss",loss)

0 iter : 2158541052480228.0
10 iter : 2.9104883045274676e+68
20 iter : 3.9244654466464395e+121
30 iter : 5.291699340610238e+174
40 iter : 7.13526014997618e+227
50 iter : 9.621094119449152e+280

loss 4.06618742972753e+291


Sklearn


In [9]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression().fit(X,Y)
# Nghiệm
LR.coef_, LR.intercept_

(array([[ 0.00000000e+00,  1.88212143e+03, -1.97331147e+01,
          1.00943796e+02, -3.53190219e+01,  1.24803173e+02,
          4.77483808e+04]]), array([-46139.64730836]))